[tool.poetry]
name = "bookstore"
version = "0.1.0"
description = "Bookstore API"
<<<<<<< HEAD
authors = ["Ramon Ortiz <ramonofcgta@gmail.com>"]
=======
authors = ["Manoela Coelho Silva <manoelacs62@gmail.com>"]
>>>>>>> 3e23122 (dcoker-networks)
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
<<<<<<< HEAD
pytest = "^8.3.3"
factory-boy = "^3.3.1"
django = "^5.1.3"
django-rest-framework = "^0.1.0"
django-extensions = "^3.2.3"
django-debug-toolbar = "^4.4.6"

=======
django = "^5.0.4"
djangorestframework = "^3.15.1"
django-extensions = "^3.2.3"
django-debug-toolbar = "^4.3.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
factory-boy = "^3.3.0"
>>>>>>> 3e23122 (dcoker-networks)

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
